### ISSUE TITLE
Test suite fails when package is loaded with only needed dependencies

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/typeset#29]
Starting GAP with option `-A` (to load only a minimal set of packages) and then loading `typeset` with only its *needed* dependencies (via `LoadPackage("typeset" : OnlyNeeded);`) leads to the test suite failing (can also be reproduced using `TestPackage("typeset" : OnlyNeeded);`

Apparently at least one of the tests expects `ctbllib` to be loaded, see the [log here](https://github.com/gap-system/PackageDistro/actions/runs/7604503774/job/20707677736).

Some possible solutions:
- force the packages to be loaded in your `tst/testall.g` file
- rewrite the test to not require `ctbllib`

**Comment by ZachNewbery** [comment]
I currently use the following snippet for the digraphs package to handle tests when the package isn't marked for loading:
```
if IsPackageMarkedForLoading( "digraphs", "1.5.0" ) then
    ReadPackage( "typeset", "gap/latex/digraphs.gi");
fi;
```
Is it worth moving the character table methods to a separate .gi file for this purpose to maintain consistency? Or perhaps explicitly adding ctblib as a 'SuggestedOtherPackages'?

**Comment by fingolfin** [comment]
Adding `ctbllib` to `SuggestedOtherPackages` does not solve the issue, as "suggested" packages may not be loaded.

I think the two options I suggested are usually the best way to tackle this.

I don't understand how your snippet about digraphs related -- that one is taken from your `init.g` and not directly related to the tests?
